<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="PAKU-BLR-01" ignored="0" name="Default test" tests="5" failures="1" timestamp="19 Oct 2022 10:16:18 GMT" time="90.076" errors="0">
  <testcase name="loginTest" time="7.995" classname="TestNgRevision.DataProviderTestNgWithExcel_9"/>
  <testcase name="loginTest" time="2.79" classname="TestNgRevision.DataProviderTestNgWithExcel_9"/>
  <testcase name="loginTest" time="2.681" classname="TestNgRevision.DataProviderTestNgWithExcel_9"/>
  <testcase name="loginTest" time="2.64" classname="TestNgRevision.DataProviderTestNgWithExcel_9"/>
  <testcase name="loginTest" time="5.72" classname="TestNgRevision.DataProviderTestNgWithExcel_9">
    <failure type="graphql.AssertException" message="condition expected to be true">
      <![CDATA[graphql.AssertException: condition expected to be true
	at graphql.Assert.assertTrue(Assert.java:85)
	at TestNgRevision.DataProviderTestNgWithExcel_9.loginTest(DataProviderTestNgWithExcel_9.java:64)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- loginTest -->
</testsuite> <!-- Default test -->
