<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="RetryAnalyzerDemo.MyTestCase1" tests="7" time="0.042" ignored="0" failures="1" timestamp="12 Sep 2022 11:55:34 GMT" skipped="3" hostname="PAKU-BLR-01" errors="0">
  <testcase name="test2" time="0.004" classname="RetryAnalyzerDemo.MyTestCase1"/>
  <testcase name="test1" time="0.018" classname="RetryAnalyzerDemo.MyTestCase1"/>
  <testcase name="test5" time="0.007" classname="RetryAnalyzerDemo.MyTestCase1">
    <skipped/>
  </testcase> <!-- test5 -->
  <testcase name="test3" time="0.005" classname="RetryAnalyzerDemo.MyTestCase1"/>
  <testcase name="test5" time="0.002" classname="RetryAnalyzerDemo.MyTestCase1">
    <skipped/>
  </testcase> <!-- test5 -->
  <testcase name="test5" time="0.002" classname="RetryAnalyzerDemo.MyTestCase1">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:305)
	at org.testng.Assert.assertEquals(Assert.java:315)
	at RetryAnalyzerDemo.MyTestCase1.test5(MyTestCase1.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:998)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1200)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- test5 -->
  <testcase name="test5" time="0.004" classname="RetryAnalyzerDemo.MyTestCase1">
    <skipped/>
  </testcase> <!-- test5 -->
</testsuite> <!-- RetryAnalyzerDemo.MyTestCase1 -->
